# Site settings
title: Computer Science 290B

description: > # this means to ignore newlines until "baseurl:"
  Scalable Internet Services, CS290B, Fall 2015

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://cs290.com" # the base hostname & protocol for your site

github_username:  scalableinternetservices

instructor: "Bryce Boe"
instructor_url: "http://bryceboe.com"

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap