# Site settings
title: CS290B
email: bboe@cs.ucsb.edu
description: > # this means to ignore newlines until "baseurl:"
  Course material for UCSB's CS290B, Scalable Internet Services
baseurl: "/ucsb_website" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  scalableinternetservices

# Build settings
markdown: kramdown
